name = 'memfeifeifei'
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true
workers_dev = false

[[kv_namespaces]]
binding = "KV"
id = "a1c661c7ae994e31868559b5d4ae6961"

# This is a test comment for auto-deployment verification

# [placement]
# region = "gcp:asia-southeast2"

[observability]
enabled = false
