name = 'follownewfei'
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true
workers_dev = false

[[kv_namespaces]]
binding = "KV"
id = "da18e2f01d4e4694a666d6457d0efb08"

# This is a test comment for auto-deployment verification

[observability]
enabled = false
